Draft PR - adding hero styles
aemsites/world-bank pull request #15
Opened 2024-08-14 11:38 UTC by arjun87743

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/
- After: https://44-herostyles--world-bank--aemsites.hlx.live/

2024-08-16 05:58 UTC, thomsebastin commented on blocks/hero/hero.css
> +.hero.block {
You can use nesting to namespace this better. For example:

```css
.hero {
    &.block {
        ... code
    }
}
```
Something like this.

2024-08-16 06:01 UTC, thomsebastin requested changes

2024-08-16 06:01 UTC, thomsebastin commented on blocks/hero/hero.js
> +  const heroContainer = document.createElement('div');
lets change to use `dom-utils` added by @rrusher. Should make it much cleaner.

2024-08-19 05:37 UTC, arjun87743 commented
@thomsebastin The scope of this ticket has changed and @skumawat1 will be working on this.

2024-08-19 15:54 UTC, thomsebastin commented
@arjun87743  kindly close the PR if not needed.

2024-08-20 05:16 UTC, closed without merging