Bugfixes - Image with Hover Cards (Five Institutions)
aemsites/world-bank pull request #278
Opened 2024-09-18 19:33 UTC by mdickson-adbe

Fix various visual issues with spacing, button colors.

Fix # https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-266, https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-271

Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/who-we-are
- After: https://bugfixes-5insts--world-bank--aemsites.hlx.live/en/who-we-are

2024-09-19 04:30 UTC, mkbansal1 requested changes
@mdickson-adbe  I see double borders on "Learn more" link
![image](https://github.com/user-attachments/assets/141b2f34-0c6b-4d0c-94a4-ee235d79da12)

2024-09-19 14:06 UTC, thomsebastin commented
@mdickson-adbe I still see the double border. Could you please have a look at this?

<img width="405" alt="Screenshot 2024-09-19 at 7 35 29 PM" src="https://github.com/user-attachments/assets/328b44c7-d5e1-4d01-9489-ad37321aeba6">

2024-09-19 14:40 UTC, mdickson-adbe commented
> @mdickson-adbe I see double borders on "Learn more" link ![image](https://private-user-images.githubusercontent.com/129100763/368841439-141b2f34-0c6b-4d0c-94a4-ee235d79da12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTY2NDksIm5iZiI6MTcyNjc1NjM0OSwicGF0aCI6Ii8xMjkxMDA3NjMvMzY4ODQxNDM5LTE0MWIyZjM0LTBjNmItNGQwYy05NGE0LWVlMjM1ZDc5ZGExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxNDMyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTc5M2EwY2JjOTlmNzAxMDg5NzBkODBjODQwNTY5YzU5YWQ3Mzg2NjZjMDkxMmU4ODVhMzgwYzJhMzQ3OGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VBuf5D7DdHbYAYpuTg4ZRygQBpyOq3BRTUz4KJkLdQw)

Please re-check. I could have sworn I removed that border-bottom but I guess I hadn't.

2024-09-23 07:56 UTC, thomsebastin commented on blocks/organizational-cards/organizational-cards.css
> +    border: 1px solid var(--primary-blue-50);
all variables that starts with `primary` are by us and we will get rid of them soon. I am approving this PR but kindly follow up with appropriate new vars in new PR.

2024-09-23 07:56 UTC, thomsebastin approved these changes

2024-09-23 11:43 UTC, mkbansal1 approved these changes

2024-09-23 11:43 UTC, merged