Homepage rtl
aemsites/world-bank pull request #328
Opened 2024-09-25 07:06 UTC by naina66406

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/
- After: https://homepage-rtl--world-bank--aemsites.hlx.live/ext/ar/home

2024-09-26 07:52 UTC, mkbansal1 approved these changes

2024-09-26 08:21 UTC, mkbansal1 requested changes
@naina66406  The language dropdown design should be
<img width="234" alt="image" src="https://github.com/user-attachments/assets/092b046a-b49f-4381-9221-41981f4d891d">
https://d3iv434a9kqur3.cloudfront.net/accessibility/WBG%20Latest/html/components/Header-ar.html

2024-09-27 05:54 UTC, naina66406 commented
Can u pls check now @mkbansal1

2024-09-27 09:27 UTC, mkbansal1 approved these changes

2024-09-27 09:27 UTC, merged