Feature + Curated Card
aemsites/world-bank pull request #38
Opened 2024-08-22 11:45 UTC by skumawat1

Fix # https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-46 ,  https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-44

Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/
- After: https://banner-cards--world-bank--aemsites.hlx.live/

author-url: https://author-p136806-e1403562.adobeaemcloud.com/ui#/@worldbank/aem/universal-editor/canvas/author-p136806-e1403562.adobeaemcloud.com/content/world-bank/global/en/drafts/skumawat/curated-cards.html?ref=banner-cards

2024-08-22 14:16 UTC, thomsebastin requested changes

2024-08-22 14:16 UTC, thomsebastin commented on blocks/curated-cards/curated-cards.js
> +  moveInstrumentation(row, li);
Can be named into something meaningful.

2024-08-22 14:16 UTC, thomsebastin commented on blocks/curated-cards/curated-cards.js
> +  const childrenArray = Array.from(block.children);
name this to something else meaningful.

2024-08-23 08:29 UTC, skumawat1 reviewed
I have addressed all review comment

2024-08-23 08:29 UTC, skumawat1 commented on blocks/curated-cards/curated-cards.css
> +.feature-card picture {
done

2024-08-23 08:29 UTC, skumawat1 commented on blocks/curated-cards/curated-cards.css
> +  background: linear-gradient(1.27deg, #012740 5.95%, #0127400f 52.78% );
done

2024-08-23 08:29 UTC, skumawat1 commented on blocks/curated-cards/curated-cards.css
> +  z-index: -1;
yes this is required as we are overlaying image with this linear gradient style

2024-08-23 08:29 UTC, skumawat1 commented on blocks/curated-cards/curated-cards.css
> +  color: #fff; /* Text color for contrast */
done

2024-08-23 08:29 UTC, skumawat1 commented on blocks/curated-cards/curated-cards.css
> +  font-size: 48px;
done

2024-08-23 08:29 UTC, skumawat1 commented on blocks/curated-cards/curated-cards.css
> +  font-size: 20px;
done

2024-08-23 13:18 UTC, mkbansal1 approved these changes

2024-08-23 14:01 UTC, thomsebastin approved these changes

2024-08-23 14:08 UTC, merged