UI updates for who we are
aemsites/world-bank pull request #39
Opened 2024-08-22 12:37 UTC by Akshaya284

Fix # https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-82

Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/en/who-we-are
- After: https://dev-who-we-are--world-bank--aemsites.hlx.live/en/who-we-are

2024-08-22 13:04 UTC, thomsebastin commented on styles/styles.css
> +    font-size: 18px !important;
Please don't use `!important`. Try increasing the specificity.

2024-08-22 13:05 UTC, thomsebastin commented on styles/styles.css
> +    font-size: 18px !important;
Use variables from `styles.css`.

2024-08-22 13:05 UTC, thomsebastin commented on styles/styles.css
> +  font-size: 24px;
use variables.

2024-08-22 13:05 UTC, thomsebastin commented on blocks/columns/columns.js
> +    block.style.gap = '20px';
Can we do this directly in `CSS` file?

2024-08-22 13:06 UTC, thomsebastin commented on blocks/columns/columns.js
> +  }
I think this can be handled via CSS. Let me know if you need to connect.

2024-08-22 13:07 UTC, thomsebastin commented on blocks/columns/columns.css
> +    line-height: 28.8px;
Let's round the line-height.

2024-08-22 13:07 UTC, thomsebastin commented on blocks/columns/columns.css
> +    color: #181F25;
If you use nesting in CSS most of this can be cleaned up.

2024-08-22 13:07 UTC, thomsebastin commented on blocks/columns/columns.css
> +@media (max-width: 767px) {
Use media range notation.

2024-08-22 13:08 UTC, thomsebastin commented
@Akshaya284 Keep PR in drafts state if there are lint issues.

2024-08-22 13:26 UTC, mkbansal1 requested changes
@Akshaya284  @thomsebastin 
I suggest the following:
1. Add a dropdown in columns block "Columns Layout" with options
- Default
- 2 Column (50%,50%)
- 2 Column (33%, 66%)
- 2 Column (66%, 33%)
- 2 Column (25%, 75%)
- 2 Column (75%, 25%)
As this will be generic layout option, we can use it with any variation
2. Add a style variation 
- Vertical bar on 2nd column

No Javascript handling needed for above, just use CSS.

2024-08-23 04:45 UTC, Akshaya284 commented
> @Akshaya284 Keep PR in drafts state if there are lint issues.

Noted.

2024-08-23 07:07 UTC, thomsebastin commented
@mkbansal1 Will handle that in a separate PR. Thanks.

2024-08-23 12:08 UTC, thomsebastin requested changes

2024-08-23 12:08 UTC, thomsebastin commented on blocks/columns/columns.css
> +@media (width >= 900px) {
Update this media query.

2024-08-23 12:08 UTC, thomsebastin commented on blocks/columns/columns.css
> +@media (width >= 768px) and (width <= 1024px) {
Can we do `media (width <= 1024px)` and then below `media(width <= 768px)` separately?

2024-08-26 13:05 UTC, thomsebastin approved these changes

2024-08-26 16:29 UTC, mkbansal1 approved these changes

2024-08-26 16:29 UTC, merged